### ISSUE TITLE
Error: Runtime exited with error: exit status 1

### ISSUE THREAD

**Issue by Vadorequest** [janaz/aws-lambda-node-runtime#4]
I successfully deployed a runtime for node 6.10.3, thanks a lot for this repository, helped me get started much faster.

I'm encountering an issue though, at runtime.

```
RequestId: 0e7ebd04-d9a3-4abf-be30-e513e494ea29 Error: Runtime exited with error: exit status 1
Runtime.ExitError
Runtime starting
START RequestId: 8583b34c-2a4b-4568-8f4f-a4d549fca400 Version: $LATEST
Failed to send the response TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Promise (/opt/runtime.js:26:22)
    at request (/opt/runtime.js:19:10)
    at sendSuccessResponse (/opt/runtime.js:78:3)
    at callHandler.then (/opt/runtime.js:171:18)
    at process._tickCallback (internal/process/next_tick.js:109:7)
2019-04-09 11:26:32 request received http://staging.unly.org/favicon.ico
2019-04-09 11:26:32 serving page http://staging.unly.org/favicon.ico
Failed to send the response TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Promise (/opt/runtime.js:26:22)
    at request (/opt/runtime.js:19:10)
    at sendSuccessResponse (/opt/runtime.js:78:3)
    at callHandler.then (/opt/runtime.js:171:18)
    at process._tickCallback (internal/process/next_tick.js:109:7)
2019-04-09 11:26:32 page served http://staging.unly.org/favicon.ico
next-warm-up-time: 376.293ms

/var/task/node_modules/aws-serverless-express/index.js:87
            context.succeed(successResponse)
                    ^
TypeError: context.succeed is not a function
    at IncomingMessage.response.on.on (/var/task/node_modules/aws-serverless-express/index.js:87:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
END RequestId: 8583b34c-2a4b-4568-8f4f-a4d549fca400
REPORT RequestId: 8583b34c-2a4b-4568-8f4f-a4d549fca400  Duration: 481.14 ms     Billed Duration: 500 ms         Memory Size: 1024 MB    Max Memory Used: 98 MB  

RequestId: 8583b34c-2a4b-4568-8f4f-a4d549fca400 Error: Runtime exited with error: exit status 1
Runtime.ExitError
Runtime starting

```

I don't get those errors when using the native nodejs6.10 AWS Lambda runtime. Any idea what could go wrong? I don't really know how to debug this.

**Comment by StoneCypher** [comment]
> Failed to send the response TypeError: Converting circular structure to JSON

you can't convert circular structures to json

```
const a = {};
const b = {toA: a};
a.toB = b;

json.stringify(a);  // will exhibit your problem
```

either stop using circular structures, or if that's not an option, use a cycle tolerant stringifier such as `util.inspect`

----

```
/var/task/node_modules/aws-serverless-express/index.js:87
            context.succeed(successResponse)
                    ^
TypeError: context.succeed is not a function
```

this one seems pretty self-explanatory

**Comment by Vadorequest** [comment]
Thank you, I know what a circular structure is, but what I don't explain is why it fails when using my custom runtime but does not fail when using the native nodejs6.10 runtime. Both should fail when encountering circular structures. 

It makes me believe there is somehow a difference between both that cause such circular structure.

**Comment by Vadorequest** [comment]
I fixed the first of those two issues by using a safe way of running JSON.stringify, see https://github.com/UnlyEd/aws-lambda-node-runtime-v6.10.3/commit/048fd9c07a6bc8b1d3412da4243a6982cbe007d6

The second exception is related to aws-serverless-express and I haven't figured it out yet: https://github.com/awslabs/aws-serverless-express/issues/230. It's not related to the source code if this repository so I could close the issue but still, I don't understand why it fails using my custom runtime and not against AWS node6.10 runtime. Still missing something, if anybody has some heads-up...

**Comment by StoneCypher** [comment]
`json-stringify-safe` is buggy and has problems

the language has native code for this which does a much better job than json stringify besides (util.inspect covers symbols and all kinds of other stuff)

**Comment by Vadorequest** [comment]
Well, good to know that the -safe way isn't actually so safe :/

**Comment by StoneCypher** [comment]
i mean, it's just sort of a truism

most libraries are buggy.  language shipped libraries tend to get much more use, and tend to have dramatically fewer bugs.

if a language ships something, it's usually much higher quality than if a third party does, and as a rule of thumb you should stick to the language one when practical

**Comment by Vadorequest** [comment]
True, but I looked for an alternative solution because I was using the native JSON.stringify, which doesn't handle recursive reference and fails because of it. So, it totally made sense to use a library in this case.

**Comment by StoneCypher** [comment]
i don't understand where the miscommunication is here

what i'm trying to explain is that there is something built into node called `util.inspect` for the specific purpose of handling this.  it does a much better job than that library, and isn't buggy.

[nodejs.org/api/util.html](https://nodejs.org/api/util.html#util_util_inspect_object_options)

**Comment by Vadorequest** [comment]
Thanks, I had misunderstood your statement indeed, it's much clearer now.

I wonder why the native `util` library isn't more famous, it's not common to see it used. I guess that's because it's only natively available for node.js and not the browser, so it's not "universal". (Even if apparently browserify/webpack support it)

**Comment by StoneCypher** [comment]
> I wonder why the native util library isn't more famous, it's not common to see it used.

people just don't leave debug statements in their code.  it's very common.

.

> (Even if apparently browserify/webpack support it)

browserify and webpack don't support things.  they aren't that important.  they're just bundlers
